#pragma config(Motor,  port1,           RightDriveMotor, tmotorVex393_HBridge, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port2,           LeftArmMotor,  tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port4,           ClawMotor,     tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port5,           MiddleMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightArmMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LeftDriveMotor, tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		motor[LeftDriveMotor] = vexRT[Ch3]; // This piece of code assigns LDM motor and RDM motor to channels on the controller
		motor[RightDriveMotor] = vexRT[Ch2];

		if(vexRT[Btn8L] == 1) // If else statement programs the claw to open and close when certain buttons are pressed
		{
			motor[ClawMotor] = -127;
		}
		else if(vexRT[Btn8R] == 1)
		{
			motor[ClawMotor] = 127;
		}
		else
		{
			motor[ClawMotor] = 0;
		}

		if(vexRT[Btn5U] == 1)// if else statement programs the arm to move up and down when certains buttons are pressed
		{
			motor[LeftArmMotor] = 127;
			motor[RightArmMotor] = -127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[LeftArmMotor] = -127;
			motor[RightArmMotor] = 127;
		}
		else
		{
			motor[LeftArmMotor] = 0;
			motor[LeftArmMotor] = 0;
		}

		if(vexRT[Btn7L] == 1) // If else statement programs the middle wheel to move left and right when certain buttons are pressed
		{
			motor[MiddleMotor] = 127;
		}
		else if(vexRT[Btn7R] == 1)
		{
			motor[MiddleMotor] = -127;
		}
		else
		{
			motor[MiddleMotor] = 0;
		}
	}
}
